version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "3001:3001"

  attendance-service:
    build:
      context: ./attendance-service
    ports:
      - "3002:3002"

  results-service:
    build:
      context: ./results-service
    ports:
      - "3003:8080"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - user-service
      - attendance-service
      - results-service
