version: '3.8'

services:
  results-service:
    build:
      context: ./results-service
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mysql

  attendance-service:
    build:
      context: ./attendance-service
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - mysql

  user-service:
    build:
      context: ./user-service
    ports:
      - "3001:3001"
    networks:
      - app-network

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school
    networks:
      - app-network
    ports:
      - "3306:3306"

networks:
  app-network:
    driver: bridge
