version: '3'
services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "3001:3001"
    networks:
      - app-network

  attendance-service:
    build:
      context: ./attendance-service
    networks:
      - app-network

  results-service:
    build:
      context: ./results-service
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - user-service
      - attendance-service
      - results-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
