version: '3'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "3001:3001"

  attendance-service:
    build:
      context: ./attendance-service
    ports:
      - "3002:3002"

  results-service:
    build:
      context: ./results-service
    ports:
      - "3003:3003"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - user-service
      - attendance-service
      - results-service
