version: '3'
services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    networks:
      - backend

  attendance-service:
    build: ./attendance-service
    networks:
      - backend
    restart: always

  results-service:
    build: ./results-service
    networks:
      - backend
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - user-service
      - attendance-service
      - results-service

networks:
  backend:
    driver: bridge
